### ISSUE TITLE
Some subroutines missing problem

### ISSUE THREAD

**Issue by JustusvLiebig** [aysunrhn/Adaptive-Soft-Sensor-Design#1]
To Miss Urhan:
      I am a beginner in the soft sensor yield and thanks gratitude for your code in the git for me to learn the concerning knowledge. 
      When I attempted to run the "Demo.M" in the code file, the issue that the “auto” function wa missed in "Subprediction.M" in Line 4. Therein, I tried to create another M file as follow:

function [Xsc, mx, sx] = auto(Xtrain)
mx = zeros(1, size(Xtrain,2));
sx = zeros(1, size(Xtrain,2));
Xsc = zeros(size(Xtrain,1), size(Xtrain,2));
for i = 1 : size(Xtrain, 2)
    mx(1, i) = mean(Xtrain(:, i));
    sx(1, i) = std(Xtrain(:, i));
end
for i = 1 : size(Xtrain, 2)
    Xsc(:, i) = (Xtrain(:, i) - mx(1, i))/ sx(1, i);
end

      After solving this, another issued occured that the “scale.m” function is missed. Therefore, I have two problems as follow:
1, Is the “auto.M” I wrote in a proper way?
2, Would you like to provide other missing function in the Code file?
      With great appreciate for reading my issue. I am looking forward to your favourable reply, 
Sincerely, Justus
July 2nd, 2020

**Comment by aysunrhn** [comment]
Hi Justus,

Yes indeed, auto function is simply for autoscaling the data. Scale is also for the same purpose of scaling, but the arguments are the center and spread values. 

Both functions are from the [PLS toolbox](https://www.mathworks.com/products/connections/product_detail/pls-toolbox.html) for matlab, but they are pretty straightforward so there is no need for the toolbox anyways but back then when I was writing this code I was using PLS toolbox quite frequently, so it came in handy., I never noticed that I hadn't mentioned this anywhere in the repo, my apologies!

**Comment by JustusvLiebig** [comment]
To Miss  Urhan:
      Thank you for your replying, I found the “scale.m” in the OEOA Toolbox, which makes the code in your repo run successfully. The scale.m are defined as follow:
function sx = scale(x,means,stds)
%SCALE Scales matrix as specified.
%  Scales a matrix (x) using means (mx) and standard 
%  deviations (stds) specified.
%
%I/O:  sx = scale(x,mx,stdx);
%
%  If only two input arguments are supplied then the function
%  will not do variance scaling, but only vector subtraction.
%
%I/O:  sx = scale(x,mx);
%
%See also: AUTO, MDAUTO, MDMNCN, MDRESCAL, MDSCALE, MNCN, RESCALE

%Copyright Eigenvector Research, Inc. 1991-98
%Modified 11/93 
%Checked on MATLAB 5 by BMW  1/4/97

[m,n] = size(x);
if nargin == 3
  sx = (x-means(ones(m,1),:))./stds(ones(m,1),:);
else
  sx = (x-means(ones(m,1),:));
end

      With great appreciate for replying me.
Sincerely, Justus
July 2nd, 2020
