### ISSUE TITLE
the function of 'auto'equal to [Z,mu,sigma] = zscore(___)？

### ISSUE THREAD

**Issue by huiyongyong** [aysunrhn/Adaptive-Soft-Sensor-Design#3]

**Comment by aysunrhn** [comment]
I think it should be, according to the matlab documentation: https://www.mathworks.com/help/stats/zscore.html

![image](https://user-images.githubusercontent.com/25639243/121363643-6d5b0d00-c937-11eb-9b0f-3b75269539e4.png)

**Comment by huiyongyong** [comment]
Ok, thank you very much!


| |
hyylut
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/9/2021 21:30，Aysun ***@***.***> wrote：

I think it should be, according to the matlab documentation: https://www.mathworks.com/help/stats/zscore.html

**Comment by huiyongyong** [comment]
| |
hyylut
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/9/2021 ***@***.***> wrote：
Ok, thank you very much!


| |
hyylut
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/9/2021 21:30，Aysun ***@***.***> wrote：

I think it should be, according to the matlab documentation: https://www.mathworks.com/help/stats/zscore.html
